// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package apiconnector.actions;

import apiconnector.impl.ApiConnector;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class ApiStatus404NotFound extends CustomJavaAction<java.lang.Boolean>
{
	public ApiStatus404NotFound(IContext context)
	{
		super(context);
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE

        logger.info(String.format("transaction id: %s", getContext().getTransactionId()));
        logger.info(String.format("transaction id: %s", getContext().getExecutionThread().toString()));
        ApiConnector connector = new ApiConnector();
        connector.setApiStateUnknownResource(getContext());
        return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "ApiStatus404NotFound";
	}

	// BEGIN EXTRA CODE
    private static final ILogNode logger = Core.getLogger(ApiStatus404NotFound.class.getName());
	// END EXTRA CODE
}
