// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package apiconnector.actions;

import apiconnector.impl.ApiConnector;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class RegisterApiEndpointWithMappings extends CustomJavaAction<Boolean>
{
	private String UrlPattern;
	private String MicroflowName;
	private Boolean SupportsGET;
	private Boolean SupportsPOST;
	private Boolean SupportsPUT;
	private Boolean SupportsDELETE;
	private Boolean SupportsPATCH;
	private String RequestMappingName;
	private IMendixObject RequestEntity;
	private String ResponseMappingName;
	private IMendixObject ResponseEntity;

	public RegisterApiEndpointWithMappings(IContext context, String UrlPattern, String MicroflowName, Boolean SupportsGET, Boolean SupportsPOST, Boolean SupportsPUT, Boolean SupportsDELETE, Boolean SupportsPATCH, String RequestMappingName, IMendixObject RequestEntity, String ResponseMappingName, IMendixObject ResponseEntity)
	{
		super(context);
		this.UrlPattern = UrlPattern;
		this.MicroflowName = MicroflowName;
		this.SupportsGET = SupportsGET;
		this.SupportsPOST = SupportsPOST;
		this.SupportsPUT = SupportsPUT;
		this.SupportsDELETE = SupportsDELETE;
		this.SupportsPATCH = SupportsPATCH;
		this.RequestMappingName = RequestMappingName;
		this.RequestEntity = RequestEntity;
		this.ResponseMappingName = ResponseMappingName;
		this.ResponseEntity = ResponseEntity;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        ApiConnector connector = new ApiConnector();
        connector.addHttpEndpoint(this.UrlPattern, this.MicroflowName, this.SupportsGET, this.SupportsPOST, this.SupportsPUT, this.SupportsDELETE, this.SupportsPATCH,
                this.RequestMappingName, this.RequestEntity, this.ResponseMappingName, this.ResponseEntity);
        return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "RegisterApiEndpointWithMappings";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
