// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package apiconnector.actions;

import apiconnector.impl.ApiConnector;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class RegisterApiEndpointXpathWithMappings extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String UrlPattern;
	private java.lang.String XpathQuery;
	private java.lang.Boolean SupportsGET;
	private java.lang.Boolean SupportsPOST;
	private java.lang.Boolean SupportsPUT;
	private java.lang.Boolean SupportsDELETE;
	private java.lang.Boolean SupportsPATCH;
	private java.lang.String RequestMappingName;
	private java.lang.String RequestEntity;
	private java.lang.String ResponseMappingName;
	private java.lang.String ResponseEntity;

	public RegisterApiEndpointXpathWithMappings(IContext context, java.lang.String UrlPattern, java.lang.String XpathQuery, java.lang.Boolean SupportsGET, java.lang.Boolean SupportsPOST, java.lang.Boolean SupportsPUT, java.lang.Boolean SupportsDELETE, java.lang.Boolean SupportsPATCH, java.lang.String RequestMappingName, java.lang.String RequestEntity, java.lang.String ResponseMappingName, java.lang.String ResponseEntity)
	{
		super(context);
		this.UrlPattern = UrlPattern;
		this.XpathQuery = XpathQuery;
		this.SupportsGET = SupportsGET;
		this.SupportsPOST = SupportsPOST;
		this.SupportsPUT = SupportsPUT;
		this.SupportsDELETE = SupportsDELETE;
		this.SupportsPATCH = SupportsPATCH;
		this.RequestMappingName = RequestMappingName;
		this.RequestEntity = RequestEntity;
		this.ResponseMappingName = ResponseMappingName;
		this.ResponseEntity = ResponseEntity;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        ApiConnector connector = new ApiConnector();
        connector.addHttpEndpoint(this.UrlPattern, null,  this.XpathQuery, null, this.SupportsGET, this.SupportsPOST, this.SupportsPUT, this.SupportsDELETE, this.SupportsPATCH,
                this.RequestMappingName, this.RequestEntity, this.ResponseMappingName, this.ResponseEntity);
        return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "RegisterApiEndpointXpathWithMappings";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
