// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package apiconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import apiconnector.impl.ApiConnector;

public class RegisterApiEndpoint extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String UrlPattern;
	private java.lang.String MicroflowName;
	private java.lang.Boolean SupportsGET;
	private java.lang.Boolean SupportsPOST;

	public RegisterApiEndpoint(IContext context, java.lang.String UrlPattern, java.lang.String MicroflowName, java.lang.Boolean SupportsGET, java.lang.Boolean SupportsPOST)
	{
		super(context);
		this.UrlPattern = UrlPattern;
		this.MicroflowName = MicroflowName;
		this.SupportsGET = SupportsGET;
		this.SupportsPOST = SupportsPOST;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        ApiConnector connector = new ApiConnector();
        connector.addHttpEndpoint(this.UrlPattern,this.MicroflowName,this.SupportsGET,this.SupportsPOST);
        return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "RegisterApiEndpoint";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
