// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies;

public class OrderLine
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject orderLineMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Main.OrderLine";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Amount("Amount"),
		Price("Price"),
		OrderLines_Orders("Main.OrderLines_Orders"),
		OrderLines_Products("Main.OrderLines_Products");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OrderLine(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Main.OrderLine"));
	}

	protected OrderLine(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject orderLineMendixObject)
	{
		if (orderLineMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Main.OrderLine", orderLineMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Main.OrderLine");

		this.orderLineMendixObject = orderLineMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'OrderLine.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static main.proxies.OrderLine initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return main.proxies.OrderLine.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static main.proxies.OrderLine initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new main.proxies.OrderLine(context, mendixObject);
	}

	public static main.proxies.OrderLine load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return main.proxies.OrderLine.initialize(context, mendixObject);
	}

	public static java.util.List<main.proxies.OrderLine> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<main.proxies.OrderLine> result = new java.util.ArrayList<main.proxies.OrderLine>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Main.OrderLine" + xpathConstraint))
			result.add(main.proxies.OrderLine.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Amount
	 */
	public final java.lang.Integer getAmount()
	{
		return getAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of Amount
	 */
	public final java.lang.Integer getAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Amount.toString());
	}

	/**
	 * Set value of Amount
	 * @param amount
	 */
	public final void setAmount(java.lang.Integer amount)
	{
		setAmount(getContext(), amount);
	}

	/**
	 * Set value of Amount
	 * @param context
	 * @param amount
	 */
	public final void setAmount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer amount)
	{
		getMendixObject().setValue(context, MemberNames.Amount.toString(), amount);
	}

	/**
	 * @return value of Price
	 */
	public final java.math.BigDecimal getPrice()
	{
		return getPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of Price
	 */
	public final java.math.BigDecimal getPrice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Price.toString());
	}

	/**
	 * Set value of Price
	 * @param price
	 */
	public final void setPrice(java.math.BigDecimal price)
	{
		setPrice(getContext(), price);
	}

	/**
	 * Set value of Price
	 * @param context
	 * @param price
	 */
	public final void setPrice(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal price)
	{
		getMendixObject().setValue(context, MemberNames.Price.toString(), price);
	}

	/**
	 * @return value of OrderLines_Orders
	 */
	public final main.proxies.Order getOrderLines_Orders() throws com.mendix.core.CoreException
	{
		return getOrderLines_Orders(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderLines_Orders
	 */
	public final main.proxies.Order getOrderLines_Orders(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.Order result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OrderLines_Orders.toString());
		if (identifier != null)
			result = main.proxies.Order.load(context, identifier);
		return result;
	}

	/**
	 * Set value of OrderLines_Orders
	 * @param orderlines_orders
	 */
	public final void setOrderLines_Orders(main.proxies.Order orderlines_orders)
	{
		setOrderLines_Orders(getContext(), orderlines_orders);
	}

	/**
	 * Set value of OrderLines_Orders
	 * @param context
	 * @param orderlines_orders
	 */
	public final void setOrderLines_Orders(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.Order orderlines_orders)
	{
		if (orderlines_orders == null)
			getMendixObject().setValue(context, MemberNames.OrderLines_Orders.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.OrderLines_Orders.toString(), orderlines_orders.getMendixObject().getId());
	}

	/**
	 * @return value of OrderLines_Products
	 */
	public final main.proxies.Product getOrderLines_Products() throws com.mendix.core.CoreException
	{
		return getOrderLines_Products(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderLines_Products
	 */
	public final main.proxies.Product getOrderLines_Products(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.Product result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OrderLines_Products.toString());
		if (identifier != null)
			result = main.proxies.Product.load(context, identifier);
		return result;
	}

	/**
	 * Set value of OrderLines_Products
	 * @param orderlines_products
	 */
	public final void setOrderLines_Products(main.proxies.Product orderlines_products)
	{
		setOrderLines_Products(getContext(), orderlines_products);
	}

	/**
	 * Set value of OrderLines_Products
	 * @param context
	 * @param orderlines_products
	 */
	public final void setOrderLines_Products(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.Product orderlines_products)
	{
		if (orderlines_products == null)
			getMendixObject().setValue(context, MemberNames.OrderLines_Products.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.OrderLines_Products.toString(), orderlines_products.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return orderLineMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final main.proxies.OrderLine that = (main.proxies.OrderLine) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Main.OrderLine";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
