// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies;

public class OrderOverview
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject orderOverviewMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Main.OrderOverview";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CustomerName("CustomerName"),
		OrderDate("OrderDate"),
		BillingAddress("BillingAddress"),
		ShippingAddress("ShippingAddress");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OrderOverview(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Main.OrderOverview"));
	}

	protected OrderOverview(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject orderOverviewMendixObject)
	{
		if (orderOverviewMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Main.OrderOverview", orderOverviewMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Main.OrderOverview");

		this.orderOverviewMendixObject = orderOverviewMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'OrderOverview.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static main.proxies.OrderOverview initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return main.proxies.OrderOverview.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static main.proxies.OrderOverview initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new main.proxies.OrderOverview(context, mendixObject);
	}

	public static main.proxies.OrderOverview load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return main.proxies.OrderOverview.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CustomerName
	 */
	public final java.lang.String getCustomerName()
	{
		return getCustomerName(getContext());
	}

	/**
	 * @param context
	 * @return value of CustomerName
	 */
	public final java.lang.String getCustomerName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CustomerName.toString());
	}

	/**
	 * Set value of CustomerName
	 * @param customername
	 */
	public final void setCustomerName(java.lang.String customername)
	{
		setCustomerName(getContext(), customername);
	}

	/**
	 * Set value of CustomerName
	 * @param context
	 * @param customername
	 */
	public final void setCustomerName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String customername)
	{
		getMendixObject().setValue(context, MemberNames.CustomerName.toString(), customername);
	}

	/**
	 * @return value of OrderDate
	 */
	public final java.util.Date getOrderDate()
	{
		return getOrderDate(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderDate
	 */
	public final java.util.Date getOrderDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.OrderDate.toString());
	}

	/**
	 * Set value of OrderDate
	 * @param orderdate
	 */
	public final void setOrderDate(java.util.Date orderdate)
	{
		setOrderDate(getContext(), orderdate);
	}

	/**
	 * Set value of OrderDate
	 * @param context
	 * @param orderdate
	 */
	public final void setOrderDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date orderdate)
	{
		getMendixObject().setValue(context, MemberNames.OrderDate.toString(), orderdate);
	}

	/**
	 * @return value of BillingAddress
	 */
	public final java.lang.String getBillingAddress()
	{
		return getBillingAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of BillingAddress
	 */
	public final java.lang.String getBillingAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BillingAddress.toString());
	}

	/**
	 * Set value of BillingAddress
	 * @param billingaddress
	 */
	public final void setBillingAddress(java.lang.String billingaddress)
	{
		setBillingAddress(getContext(), billingaddress);
	}

	/**
	 * Set value of BillingAddress
	 * @param context
	 * @param billingaddress
	 */
	public final void setBillingAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String billingaddress)
	{
		getMendixObject().setValue(context, MemberNames.BillingAddress.toString(), billingaddress);
	}

	/**
	 * @return value of ShippingAddress
	 */
	public final java.lang.String getShippingAddress()
	{
		return getShippingAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of ShippingAddress
	 */
	public final java.lang.String getShippingAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ShippingAddress.toString());
	}

	/**
	 * Set value of ShippingAddress
	 * @param shippingaddress
	 */
	public final void setShippingAddress(java.lang.String shippingaddress)
	{
		setShippingAddress(getContext(), shippingaddress);
	}

	/**
	 * Set value of ShippingAddress
	 * @param context
	 * @param shippingaddress
	 */
	public final void setShippingAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String shippingaddress)
	{
		getMendixObject().setValue(context, MemberNames.ShippingAddress.toString(), shippingaddress);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return orderOverviewMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final main.proxies.OrderOverview that = (main.proxies.OrderOverview) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Main.OrderOverview";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
