// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies;

public class ProductReport extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Main.ProductReport";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ReportName("ReportName"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ProductReport(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Main.ProductReport"));
	}

	protected ProductReport(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject productReportMendixObject)
	{
		super(context, productReportMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Main.ProductReport", productReportMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Main.ProductReport");
	}

	/**
	 * @deprecated Use 'ProductReport.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static main.proxies.ProductReport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return main.proxies.ProductReport.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static main.proxies.ProductReport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new main.proxies.ProductReport(context, mendixObject);
	}

	public static main.proxies.ProductReport load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return main.proxies.ProductReport.initialize(context, mendixObject);
	}

	public static java.util.List<main.proxies.ProductReport> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<main.proxies.ProductReport> result = new java.util.ArrayList<main.proxies.ProductReport>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Main.ProductReport" + xpathConstraint))
			result.add(main.proxies.ProductReport.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of ReportName
	 */
	public final java.lang.String getReportName()
	{
		return getReportName(getContext());
	}

	/**
	 * @param context
	 * @return value of ReportName
	 */
	public final java.lang.String getReportName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReportName.toString());
	}

	/**
	 * Set value of ReportName
	 * @param reportname
	 */
	public final void setReportName(java.lang.String reportname)
	{
		setReportName(getContext(), reportname);
	}

	/**
	 * Set value of ReportName
	 * @param context
	 * @param reportname
	 */
	public final void setReportName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reportname)
	{
		getMendixObject().setValue(context, MemberNames.ReportName.toString(), reportname);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final main.proxies.ProductReport that = (main.proxies.ProductReport) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Main.ProductReport";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
