// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies;

public class ProductImage extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Main.ProductImage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ImageName("ImageName"),
		Filename("Filename"),
		ContentType("ContentType"),
		ImageId("ImageId"),
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		ProductImage_Product("Main.ProductImage_Product");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ProductImage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Main.ProductImage"));
	}

	protected ProductImage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject productImageMendixObject)
	{
		super(context, productImageMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Main.ProductImage", productImageMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Main.ProductImage");
	}

	/**
	 * @deprecated Use 'ProductImage.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static main.proxies.ProductImage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return main.proxies.ProductImage.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static main.proxies.ProductImage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new main.proxies.ProductImage(context, mendixObject);
	}

	public static main.proxies.ProductImage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return main.proxies.ProductImage.initialize(context, mendixObject);
	}

	public static java.util.List<main.proxies.ProductImage> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<main.proxies.ProductImage> result = new java.util.ArrayList<main.proxies.ProductImage>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Main.ProductImage" + xpathConstraint))
			result.add(main.proxies.ProductImage.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of ImageName
	 */
	public final java.lang.String getImageName()
	{
		return getImageName(getContext());
	}

	/**
	 * @param context
	 * @return value of ImageName
	 */
	public final java.lang.String getImageName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ImageName.toString());
	}

	/**
	 * Set value of ImageName
	 * @param imagename
	 */
	public final void setImageName(java.lang.String imagename)
	{
		setImageName(getContext(), imagename);
	}

	/**
	 * Set value of ImageName
	 * @param context
	 * @param imagename
	 */
	public final void setImageName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String imagename)
	{
		getMendixObject().setValue(context, MemberNames.ImageName.toString(), imagename);
	}

	/**
	 * @return value of Filename
	 */
	public final java.lang.String getFilename()
	{
		return getFilename(getContext());
	}

	/**
	 * @param context
	 * @return value of Filename
	 */
	public final java.lang.String getFilename(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Filename.toString());
	}

	/**
	 * Set value of Filename
	 * @param filename
	 */
	public final void setFilename(java.lang.String filename)
	{
		setFilename(getContext(), filename);
	}

	/**
	 * Set value of Filename
	 * @param context
	 * @param filename
	 */
	public final void setFilename(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String filename)
	{
		getMendixObject().setValue(context, MemberNames.Filename.toString(), filename);
	}

	/**
	 * @return value of ContentType
	 */
	public final java.lang.String getContentType()
	{
		return getContentType(getContext());
	}

	/**
	 * @param context
	 * @return value of ContentType
	 */
	public final java.lang.String getContentType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContentType.toString());
	}

	/**
	 * Set value of ContentType
	 * @param contenttype
	 */
	public final void setContentType(java.lang.String contenttype)
	{
		setContentType(getContext(), contenttype);
	}

	/**
	 * Set value of ContentType
	 * @param context
	 * @param contenttype
	 */
	public final void setContentType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String contenttype)
	{
		getMendixObject().setValue(context, MemberNames.ContentType.toString(), contenttype);
	}

	/**
	 * @return value of ImageId
	 */
	public final java.lang.Long getImageId()
	{
		return getImageId(getContext());
	}

	/**
	 * @param context
	 * @return value of ImageId
	 */
	public final java.lang.Long getImageId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ImageId.toString());
	}

	/**
	 * Set value of ImageId
	 * @param imageid
	 */
	public final void setImageId(java.lang.Long imageid)
	{
		setImageId(getContext(), imageid);
	}

	/**
	 * Set value of ImageId
	 * @param context
	 * @param imageid
	 */
	public final void setImageId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long imageid)
	{
		getMendixObject().setValue(context, MemberNames.ImageId.toString(), imageid);
	}

	/**
	 * @return value of ProductImage_Product
	 */
	public final main.proxies.Product getProductImage_Product() throws com.mendix.core.CoreException
	{
		return getProductImage_Product(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductImage_Product
	 */
	public final main.proxies.Product getProductImage_Product(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.Product result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProductImage_Product.toString());
		if (identifier != null)
			result = main.proxies.Product.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProductImage_Product
	 * @param productimage_product
	 */
	public final void setProductImage_Product(main.proxies.Product productimage_product)
	{
		setProductImage_Product(getContext(), productimage_product);
	}

	/**
	 * Set value of ProductImage_Product
	 * @param context
	 * @param productimage_product
	 */
	public final void setProductImage_Product(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.Product productimage_product)
	{
		if (productimage_product == null)
			getMendixObject().setValue(context, MemberNames.ProductImage_Product.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProductImage_Product.toString(), productimage_product.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final main.proxies.ProductImage that = (main.proxies.ProductImage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Main.ProductImage";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
